### PR TITLE
Updates for Visual Studio 2015

### PR DESCRIPTION
**Pull request by prisonerjohn**
Fixed a bit of code and added/updated project files for all examples.

### CODE REVIEW

**Comment by NickHardeman** [comment]
Will this maintain vs 2012 support? or just 2015?

**Comment by prisonerjohn** [comment]
Only 2015, I updated all the project files. Is this fine? I figured it would be since OF 0.9.0 only supports the latest Visual Studio.

**Comment by NickHardeman** [comment]
This is great. I think I'm going to make a release first, in case people want to use vs 2012 and soft bodies. And then moving forward we can just target 009.

**Comment by prisonerjohn** [comment]
OK cool. You might want to cherry pick 55d89e345f77cc1aa3705a042c86180321144fa0 in that release, or else the SoftTriMesh won't work on Windows.

**Comment by prisonerjohn** [comment]
Also: maybe we can get rid of the crappy SoftBodyExample I made :) The ClothExample looks much better and uses the same components

**Comment by NickHardeman** [comment]
We can drop the example if you want. Committing to OF 009 now, so no need for vs2012 support.

**Pull request merged**
