### PR TITLE
Soft Bodies!

### PR DESCRIPTION
**Pull request by prisonerjohn**
Alright, finally got this together:
* ofxBulletRigidBody is the base shape for rigid bodies.
* ofxBulletSoftBody is the base shape for soft bodies.
* ofxBulletBaseShape is now the base class for ofxBulletRigidBody and ofxBulletSoftBody.
* I added three types of soft bodies: ofxBulletRope,  ofxBulletPatch (Cloth), and  ofxBulletEllipsoid.
* Soft bodies are backed by an ofMesh for rendering (even added normals!)

I'm on Windows right now, so only EmptyExample and SoftBodyExample on VS 2012 will compile and run properly. The new files still need to be added to the other projects.

### CODE REVIEW

**Comment by prisonerjohn** [comment]
Just added some Xcode project files for this. (back on Mac at my studio)

**Comment by NickHardeman** [comment]
Hi @prisonerjohn,
This looks great. 
A few thoughts:
- It would be great to be able to support compatibility for older versions of ofxBullet and apply settings like damping to all of the shapes. So putting more universal functions like add(), setDamping, getDamping, getMass, applyForce, applyCentralForce into ofxBulletBaseShape will be easier for looping through a vector of ofxBulletBaseShapes and setting all of those functions without having to query the type and casting it.
- The convention for the rigid bodies for their create function was BulletWorld*, ofVec3f location, float mass, etc. I noticed that this was not the case in the soft bodies. Is it possible to add this in?

**Comment by prisonerjohn** [comment]
Hey! Yes and yes. I tried to keep parity with what was already there, but these slipped through. I'll get to it in the next few days.

**Comment by prisonerjohn** [comment]
Well it took a little longer than expected, but I'm finally looking at this again :)

I just took a closer look at your two notes and remembered why I did things the way I did:

* I tried putting in as much of the stuff that's common to soft and rigid bodies in `ofxBulletBaseShape`, but the methods you're listing above only apply to [btRigidBody](http://www.continuousphysics.com/Bullet/BulletFull/classbtRigidBody.html) and not [btSoftBody](http://www.continuousphysics.com/Bullet/BulletFull/classbtSoftBody.html). We could add empty implementations for these methods to `ofxBulletSoftBody`, but that seems like it would be confusing more than anything. Otherwise, maybe renaming `ofxBulletBaseShape` to something different would help?

* I'm passing `ofxBulletWorldSoft` instead of `btSoftRigidDynamicsWorld` in soft body constructors because I need this extra [btSoftBodyWorldInfo](http://www.continuousphysics.com/Bullet/BulletFull/structbtSoftBodyWorldInfo.html) object to build soft bodies. I see two solutions here:
    * Pass in both `btSoftRigidDynamicsWorld` and `btSoftBodyWorldInfo` from `ofxBulletWorldSoft` into soft body constructors, but that seems like we're overcomplicating things.
    * Switch `ofxRigidBody` classes to take an `ofxBulletWorldRigid` in their constructor instead of a `btDiscreteDynamicsWorld`. I know this totally breaks backwards compatibility, but it would be consistent and simpler.

Let me know your thoughts!

**Comment by prisonerjohn** [comment]
Bump, and a screenshot of a weird tentacle creature built with soft bodies :)

screen shot 2015-03-17 at 9 19 51 am

**Comment by NickHardeman** [comment]
Sorry for the delayed response. Awesome tentacles. I'm going to take a look at what you have in your pull request in the next couple of days. 
OF 0.9.0 will probably require the bullet libs to be rebuilt to link against libc++. So maybe bundling that in with soft bodies would be a good approach, since we might not be able to provide backwards compatibility.

**Comment by prisonerjohn** [comment]
Cool! 

I saw that note yesterday too about libc++. Just so you know, I've been using ofxBullet with OF master and libc++ on Mac and it's been running fine. I don't know if that means bullet doesn't use the std lib or what exactly, but it might be good as-is.

**Pull request merged**
